"""Markdown report writer."""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from pathlib import Path

from jarvis.util.clock import now_iso


class MarkdownDocument:
    """A small builder for readable reports."""

    def __init__(self, title: str = "Report") -> None:
        self.title = title
        self._parts: list[str] = [f"# {title}", ""]

    def heading(self, text: str, level: int = 2) -> MarkdownDocument:
        self._parts.append(f"{'#' * max(1, min(6, level))} {text}")
        self._parts.append("")
        return self

    def paragraph(self, text: str) -> MarkdownDocument:
        self._parts.append(text)
        self._parts.append("")
        return self

    def bullets(self, items: Iterable[str]) -> MarkdownDocument:
        for item in items:
            self._parts.append(f"- {item}")
        self._parts.append("")
        return self

    def table(self, headers: Sequence[str], rows: Iterable[Sequence[object]]) -> MarkdownDocument:
        headers = [str(h) for h in headers]
        self._parts.append("| " + " | ".join(headers) + " |")
        self._parts.append("|" + "|".join(["---"] * len(headers)) + "|")
        for row in rows:
            cells = [str(c).replace("|", "\\|") for c in row]
            cells += [""] * (len(headers) - len(cells))
            self._parts.append("| " + " | ".join(cells[: len(headers)]) + " |")
        self._parts.append("")
        return self

    def code(self, text: str, language: str = "") -> MarkdownDocument:
        self._parts.append(f"```{language}")
        self._parts.append(text.rstrip())
        self._parts.append("```")
        self._parts.append("")
        return self

    def footer(self) -> MarkdownDocument:
        self._parts.append("---")
        self._parts.append(f"_Generated by Jarvis at {now_iso()} UTC._")
        return self

    def text(self) -> str:
        return "\n".join(self._parts).rstrip() + "\n"

    def save(self, path: str | Path) -> Path:
        dest = Path(path)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(self.text(), encoding="utf-8")
        return dest
